### ISSUE TITLE
Issues where big amounts of requests stops concurrency manager

### ISSUE THREAD

**Issue by ev8dev** [bernawil/axios-concurrency#5]
Hi,

For some reason I am having issues with the concurrency manager, when I do 60 concurrent requests with a max concurrency of 25 the whole application stops responding. I boiled it down to the concurrency manager, when I comment out the code it works fine but when using the manager it all breaks.

Not sure why it would cause that since the manager does not have that much code in it and I can't really see where it would break.

**Comment by bernawil** [comment]
Is this running in a Node server or browser? I'd suggest first watching for
memory usage with something like process.memoryUsage() in node. 25
concurrent open requests can be really problematic for a single browser tab.

This library is intended to let you forget about handling concurrency in
the consumer side, but if you know some piece of your code will produce a
high number of requests at the same time I recomend you also handle the
concurrency there using something like Bluebird's Promise.map
<http://bluebirdjs.com/docs/api/promise.map.html> mainly to save on memory.

**Comment by ev8dev** [comment]
Thank you for the fast reply, it's a Node server.

The issue with using a promise map is that the requests are made throughout the application, it's a socket server that has a connection to a rest API. Your manager did the job but for some reason it just doesn't like high amounts of requests.

Maybe I could make an internal queue and use Bluebird's Promise.map on that but I am not sure if that would be a good solution.

**Comment by bernawil** [comment]
Maybe check out this other solution https://github.com/bernawil/concurrency-control
It's more performant since it doesn't need to instantiate the request inside axios.

**Comment by andrii-melnyk-ring** [comment]
@ev8dev, it is possible related to the issue with unprocessed failed requests, which stuck in the manager. I've opened PR to fix this.

**Comment by ev8dev** [comment]
My colleague opened this but he's on holiday right now so just replying for him.

@bernawil, he will check that out when he returns, thanks!

@andrii-melnyk-ring, that would be strange since none of the requests should have failed, but it's worth a shot. Thanks for opening a PR on that!
